version: '3.3'
networks:
  traefik-public:
    external: true
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:  
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.rlab.com'
        registry_external_url 'https://registry.rlab.com'
        nginx['listen_port'] = '80'
        nginx['listen_https'] = false
        registry_nginx['listen_port'] = '80'
        registry_nginx['listen_https'] = false
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '2222:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - traefik-public
    labels:
      - traefik.docker.network=traefik-public
      - traefik.ci.frontend.rule=Host:gitlab.rlab.com
      - traefik.ci.port=80
      - traefik.ci.frontend.entryPoints=http,https
      - traefik.reg.frontend.rule=Host:registry.rlab.com
      - traefik.reg.port=80
      - traefik.reg.frontend.entryPoints=http,https
