---
- hosts: manager[0]
  become: true
  tasks:
    - name: Download Traefik Stack File
      shell: |
        curl -L https://raw.githubusercontent.com/rbales79/Docker-Swarm-Traefik/master/docker-compose.traefik.yml -o docker-compose.traefik.yml
        docker network create --driver=overlay traefik-public
        export EMAIL=rbales79@gmail.com
        export DOMAIN=rlab.local
        export USERNAME=admin
        export PASSWORD=changethis
        export HASHED_PASSWORD=$(openssl passwd -apr1 $PASSWORD)
        export CONSUL_REPLICAS=3
        export TRAEFIK_REPLICAS=3
        docker stack deploy --compose-file=docker-compose.traefik.yml Traefik-Portainer
