
---
- hosts: manager[0]
  become: true
  tasks:
    - name: Download Traefik Stack File
      shell: |
        curl -L https://raw.githubusercontent.com/rbales79/Docker-Swarm-Traefik/master/compose-traefikwip.yml -o compose-traefikwip.yml
        docker stack deploy -c compose-traefikwip.yml traefikwip
