---
- hosts: manager[0]
  become: true
  tasks:
    - name: Download Traefik Stack File
      shell: |
        export EMAIL=rbales79@gmail.com
        export DOMAIN=rlab.local
        export USERNAME=admin
        export PASSWORD=Password
        docker stack deploy --compose-file=docker-compose2.traefik.yml Traefik
