---
- name: Clone multiple VMs
  hosts: localhost 
  gather_facts: false
  vars_files: 
    test_vms.yml
  tasks: 
  - name: Clone multiple VMs from template
    local_action:
      module: vmware_guest
      hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False      
      folder: "{{ folder }}"
      template: "{{ vmtemplate }}"
      datastore: "{{ datastore }}"
      name: "{{ item }}"
      cluster: "{{ vmcluster }}"
      datacenter: "{{ datacenter }}"
      networks:
      - name: "{{ networks }}"
      disk:
      - size_gb: "{{ disk_size | default(20) }}"
        type: thin
      hardware:
        memory_mb: "{{ memory | default(8196) }}"
        num_cpus: "{{ cpus default(2) }}"
        scsi: paravirtual
      linked_clone: "{{ linked_clone }}" 
      state: poweredon
    with_items: "{{ servers }}"

