---
- name: Clone multiple VMs
  hosts: localhost 
  gather_facts: false
  vars_files: 
    test_vms.yml
  tasks: 
  - name: Clone multiple VMs from template
    module: vmware_guest  
    local_action:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False      
      folder: "{{ folder }}"
      template: "{{ vmtemplate }}"
      name: "{{ item }}"
      cluster: "{{ vmcluster }}"
      datacenter: "{{ datacenter }}"
      networks:
      - name: "{{ networks }}"
      disk:
      - size_gb: "{{ disk_size }}"
      type: thin
      hardware:
      - memory_gb: "{{ memory }}"
      - num_cpus: "{{ cpus }}"
      - scsi: paravirtual
      linked_clone: "{{ linked_clone }}" 
      state: poweredon
    with_items: "{{ servers }}"

