---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 172.16.1.5
      username: administrator@vsphere.local
      password: VMware1!
      validate_certs: False
      name: testvm_2
      template: centos7-base
      datacenter: /rlab-datacenter01
      folder: /rlab-datacenter01/ansible-vms
      state: poweredon
      wait_for_ip_address: yes
